### PR TITLE
fix: logo altered elements

### LINKED ISSUE #141: Fix display of Maidenform Logo
- [ ] Ensure the Maidenform logo is correctly displayed, might be an SVG scaling issue
- [ ] Proposal and contribution to boilerplate to provide a generic solution to this issue

Screenshot 2023-03-03 at 17 25 48

### PR DESCRIPTION
**Pull request by dicagno**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #141 

Test URLs:
- Before: https://main--maidenform--hlxsites.hlx.page/
- After: https://fix-logo-scaling--maidenform--hlxsites.hlx.page/

### CODE REVIEW

File: scripts/lib-franklin.js [hunk 1]
```diff
@@ -153,13 +164,27 @@ export async function decorateIcons(element) {
...
+
+          if (!preserveSizing) {
+            parsedSvg.documentElement.removeAttribute('width');
+            parsedSvg.documentElement.removeAttribute('height');
+          }
+
           ICONS_CACHE[iconName] = {
-            html: svg
-              .replace('<svg', `<symbol id="${iconName}"`)
-              .replace(/ width=".*?"/, '')
```
Comment (hannessolo) [inline scripts/lib-franklin.js:161]: I think instead of doing this fix, we could also just replace this part with a regex that only replaces width/heigh in the root `<svg>` tag. As the other width/heights are relative to viewbox, that should work right?

Comment (dicagno) [reply scripts/lib-franklin.js:161]: Hi @hannessolo if I understand correctly this unfortunately would not fix the issue, since for some svg elements (like the `rect` representing letter "I" in the svg for the Maidenform logo needs size to be defined (the original code strips size attributes from the `rect` element, and this was hiding the letter "I" from the logo).
Does this make sense to you?

Comment (herzog31) [reply scripts/lib-franklin.js:161]: @dicagno What @hannessolo is suggesting is to strip `height` and `width` only from the parent `svg` element, but leave it for anything inside e.g. `rect`, since the values used inside are relative to the viewbox and do not interfere with the sizing of the overall svg.

Comment (hannessolo) [reply scripts/lib-franklin.js:161]: I think replacing it with this would work:

```
svg
  .replace(/<svg([^>]+) width=".*?" ([^>]+)>/, '<svg $1 $2>')
  .replace(/<svg([^>]+) height=".*?" ([^>]+)>/, '<svg $1 $2>')
  .replace('<svg', `<symbol id="${iconName}"`)
  .replace('</svg>', '</symbol>'),
```

File: icons/logo.svg [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <?xml version="1.0" encoding="utf-8"?>
 <!-- Generator: Adobe Illustrator 26.0.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
-<svg version="1.1" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
+<svg data-preserve-sizing="true" version="1.1" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
```
Comment (herzog31) [inline icons/logo.svg:3]: With the latest commit, you can remove this `data` attribute.

**Review by herzog31 — APPROVED** [review]

File: icons/logo.svg (hunk 2 above)
Comment (dicagno) [reply icons/logo.svg:3]: leftover, true
