### PR TITLE
Fix/353 radio buttons

### LINKED ISSUE #353: Checkout: fix radio buttons
- [x] radio buttons in steps
- [x] radio buttons in payment component and payment step

Integrating the latest changes to branch issue/188 #188

### PR DESCRIPTION
**Pull request by dicagno**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #353 

Test URLs:
- https://fix-353-radio-buttons--maidenform--hlxsites.hlx.page/

### CODE REVIEW

File: scripts/configs.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 // Determine the environment
 export const calcEnvironment = () => {
+  return 'stage';
```
Comment (herzog31) [inline scripts/configs.js:3]: This should not be needed anymore.

**Review by herzog31 — APPROVED** [review]
